---
- name: Test partial array overrides
  hosts: nodes
  connection: local
  tasks:
    - name: Load generic vars
      ansible.builtin.include_vars:
        file: generic/all.yml

    - name: Patch vars
      ansible.builtin.include_tasks:
        file: tasks/loop_patch_var.yml
      loop:
        - some_var
        - some_other_var
      loop_control:
        loop_var: original_var_name

    - name: Show final some_var
      ansible.builtin.debug:
        var: some_var

    - name: Show final some_other_var
      ansible.builtin.debug:
        var: some_other_var
