---
- name: Determine variable name for overrides and extras
  ansible.builtin.set_fact:
    overrides_var_name: "{{ original_var_name }}_overrides"
    extras_var_name: "{{ original_var_name }}_extras"

- name: Patch var {{ original_var_name }} with overrides
  when: lookup('vars', overrides_var_name, default=[]) | length > 0
  block:
    - name: Retrieved overrides
      ansible.builtin.set_fact:
        overrides: "{{ lookup('vars', overrides_var_name) }}"

    - name: Clear patched_var
      ansible.builtin.set_fact:
        patched_var: []

    - name: Generate patched var
      ansible.builtin.set_fact:
        patched_var: "{{ patched_var + [item | combine(override) ] }}"
      loop: "{{ lookup('vars', original_var_name) }}"
      vars:
        override: "{{ (overrides | selectattr('name', 'equalto', item.name) | first) | default({}) }}"

    - name: Assign patched var to {{ original_var_name }}  # noqa: var-naming
      ansible.builtin.set_fact:
        "{{ original_var_name }}": "{{ patched_var }}"

- name: Add extra values to {{ original_var_name }}  # noqa: var-naming
  ansible.builtin.set_fact:
    "{{ original_var_name }}": "{{ lookup('vars', original_var_name) + [item] }}"
  loop: "{{ lookup('vars', extras_var_name, default=[]) }}"
